[package]
name = "simplecachenuker"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
glob = "0.3.1"
log = "0.4.20"
rocket = { version = "0.5.0", features = ["json"] }
tokio = { version = "1.35.1", features = ["process", "sync", "time"] }
